# Generated by Django 4.0.4 on 2023-11-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_amazonpricetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonpricetracking',
            name='tracking_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
