# Generated by Django 4.0.4 on 2023-11-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_amazonpricetracking_tracking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonpricetracking',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='amazonpricetracking',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
